[package]
name = "flavours"
description = "An easy to use base16 scheme manager/builder that integrates with any workflow."
version = "0.1.0"
authors = ["Gabriel Fontes (Misterio77) <eu@misterio.me>"]
edition = "2018"
readme = "README.md"
license = "MIT"
keywords = ["base16", "color", "color-scheme", "manager", "cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = {version = "2.33", features = ["yaml", "wrap_help", "suggestions", "color"]}
toml = "0.5"
url = "2.1"
dirs = "2.0"
anyhow = "1.0.31"
